api_key = "baae9d15af00d2c6d21f305b2753516e"
# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "1839071"

# Display settings
units = "metric"
display_symbol = "°C"
